/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mas;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author jelmer
 */
public class AgentWindow extends javax.swing.JFrame implements Agent.Listener {

    private Agent agent;
    
    /**
     * Creates new form AgentWindow
     */
    public AgentWindow()
    {
        initComponents();
        
        knowledgePage.setEditable(false);
    }
    
    public void setAgent(Agent agent)
    {
        if (this.agent != null)
            this.agent.removeListener(this);
        
        this.agent = agent;
        
        agent.addListener(this);
        
        agentChanged(agent);
    }
    
    @Override
    public void agentChanged(Agent agent)
    {
        updateName();
        
        updateCards();
        
        updateKnowledge();
    }
    
    private void updateName()
    {
        agentName.setText(agent.getName());
    }
    
    private void updateCards()
    {
        Card[] cards = agent.getHand().toArray(new Card[0]);
        JLabel[] labels = {card1, card2, card3, card4}; 
        
        for (int i = 0; i < 4; ++i) {
            if (cards.length > i)
                labels[i].setIcon(new ImageIcon(cards[i].getImage().getScaledInstance(-1, 90, Image.SCALE_SMOOTH)));
            else
                labels[i].setIcon(null);
        }
    }
    
    private void updateKnowledge()
    {
        knowledgePage.setText(agent.getThoughts());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        knowledgePage = new javax.swing.JTextArea();
        agentName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        card1 = new javax.swing.JLabel();
        card2 = new javax.swing.JLabel();
        card3 = new javax.swing.JLabel();
        card4 = new javax.swing.JLabel();

        knowledgePage.setColumns(20);
        knowledgePage.setRows(5);
        jScrollPane1.setViewportView(knowledgePage);

        agentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agentName.setText("[Naam]");

        jPanel1.setLayout(new java.awt.GridLayout());
        jPanel1.add(card1);
        jPanel1.add(card2);
        jPanel1.add(card3);
        jPanel1.add(card4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(agentName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(agentName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentName;
    private javax.swing.JLabel card1;
    private javax.swing.JLabel card2;
    private javax.swing.JLabel card3;
    private javax.swing.JLabel card4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea knowledgePage;
    // End of variables declaration//GEN-END:variables
}
