/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jelmer
 */
public class MainWindow extends javax.swing.JFrame implements Table.Listener {

    private Table table;
    
    private List<AgentWindow> windows;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow(Table table) {
        initComponents();
        initOverlay();
        
        this.table = table;
        this.setSize(1300, 900);
        
        windows = new ArrayList<AgentWindow>();
        
        for (int i = 0; i < 4; ++i) {
            AgentWindow window = new AgentWindow();
            windows.add(window);
            agentsPanel.add(window.getContentPane());
        }
        
        
    }

    public void setTable(Table table)
    {
        this.table = table;
        
        table.addListener(this);
        
        List<Agent> agents = table.getAgents();
        
        assert agents.size() <= windows.size() : "There are not enough windows for all these agents";
        
        for (int i = 0; i < agents.size(); ++i)
            windows.get(i).setAgent(agents.get(i));
    }
    
    @Override
    public void tableChanged(Table table)
    {
        setTable(table);
    }
    
    @Override
    public void tableHasWinner(Table table, Agent agent)
    {
        overlayText.setText(agent + " has won");
        overlay.setVisible(true);
    }
    
    private void initOverlay()
    {
        setGlassPane(overlay);
        
        overlay.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                overlay.setVisible(false);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overlay = new javax.swing.JPanel();
        overlayText = new javax.swing.JLabel();
        overlayHint = new javax.swing.JLabel();
        agentsPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();

        overlay.setPreferredSize(null);

        overlayText.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        overlayText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overlayText.setText("Agent X has won");

        overlayHint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        overlayHint.setText("Click to continue");
        overlayHint.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        overlayHint.setMaximumSize(null);
        overlayHint.setMinimumSize(null);

        org.jdesktop.layout.GroupLayout overlayLayout = new org.jdesktop.layout.GroupLayout(overlay);
        overlay.setLayout(overlayLayout);
        overlayLayout.setHorizontalGroup(
            overlayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(overlayLayout.createSequentialGroup()
                .addContainerGap()
                .add(overlayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(overlayText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(overlayHint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        overlayLayout.setVerticalGroup(
            overlayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(overlayLayout.createSequentialGroup()
                .addContainerGap()
                .add(overlayText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(overlayHint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 243, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ezelen");

        agentsPanel.setLayout(new java.awt.GridLayout(1, 0));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(agentsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(nextButton)
                        .add(0, 227, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(agentsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nextButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        table.playRound();
    }//GEN-LAST:event_nextButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agentsPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel overlay;
    private javax.swing.JLabel overlayHint;
    private javax.swing.JLabel overlayText;
    // End of variables declaration//GEN-END:variables
}
